
name: 'exec-script-dev-container'
description:  'this command runs a script inside the devcontainer'
inputs:
    workspace-folder:
        description: 'The workspace folder'
        default: "${PWD}"
    container-name:
        description: 'The name of the container'
        default: "devcontainer"
    script-path:
        description: 'The path to the script to run'
runs:
    using: 'composite'
    steps:
        - name: Run script inside devcontainer
          shell: bash
          run: |
            echo "Script path: ${{ inputs.script-path }}"
            echo "Container name: ${{ inputs.container-name }}"
            echo "Workspace folder: ${{ inputs.workspace-folder }}"
            echo "Running script inside devcontainer..."
            devcontainer exec "${{ inputs.script-path }}" --workspace-folder ${{ inputs.workspace-folder }}