name: Test Installing regctl
on: 
    workflow_call:
      inputs:
        agent:
          description: 'The agent to run the job on'
          required: true
          type: string

jobs:
  test-install-regctl:
    runs-on: ${{ inputs.agent }}

    steps:
    - uses: actions/checkout@v2

    - uses: mack-bytes-government/bicep-environment-templates/composite-actions/install-regctl@install-regctl-latest
      with:
        reg_ctl_version: "v0.8.2"

    - name: Validate regctl
      shell: bash
      run: |
        VERSION_COMMAND_OUTPUT=$(regctl version)
        INSTALLED_VER=$(echo $VERSION_COMMAND_OUTPUT | awk '{print $2}')

        # Compare the installed version with the required version
        VER_REGCTL="v0.8.2"
        if [ "$INSTALLED_VER" == "$VER_REGCTL" ]; then
            echo "Version matches"
        else
            echo "Version does not match. Installed version is $INSTALLED_VER but required version is $VER_REGCTL"
            exit 1
        fi
        